package demo

import (
	"context"
	"errors"
	"fmt"
	"time"

	"github.com/evilgenius79/fable-tailscale/internal/model"
	"github.com/evilgenius79/fable-tailscale/internal/store"
)

// backfillBatch is the number of samples inserted per transaction.
const backfillBatch = 2000

// prevCounters remembers the previous sample's counters per device so
// backfilled rates match what the collector computes live (delta/step).
type prevCounters struct {
	ok       bool
	counters [nFlows]float64
}

// Backfill seeds st with synthetic history when it holds no samples: one
// model.Sample per device per step from now-d to now, generated by the same
// deterministic functions that drive the live sources, so live data
// continues the history seamlessly. Devices are upserted with FirstSeen set
// to the start of the backfilled range. It is a no-op (nil error) when the
// store already has samples or d <= 0.
func (s *Sim) Backfill(ctx context.Context, st *store.Store, d, step time.Duration) error {
	if st == nil {
		return errors.New("demo: backfill: nil store")
	}
	if step <= 0 {
		return fmt.Errorf("demo: backfill: invalid step %v", step)
	}
	stepSec := int64(step / time.Second)
	if stepSec < 1 {
		return fmt.Errorf("demo: backfill: step %v is below one second", step)
	}
	if d <= 0 {
		s.log.Debug("backfill skipped: non-positive duration", "duration", d)
		return nil
	}
	if err := ctx.Err(); err != nil {
		return fmt.Errorf("demo: backfill: %w", err)
	}

	stats, err := st.Stats(ctx)
	if err != nil {
		return fmt.Errorf("demo: backfill: store stats: %w", err)
	}
	if stats.Samples > 0 {
		s.log.Info("backfill skipped: store already has samples", "samples", stats.Samples)
		return nil
	}

	s.mu.Lock()
	now := s.tick()
	devs := make([]*device, 0, len(s.devs))
	for _, dev := range s.devs {
		if !dev.deleted {
			devs = append(devs, dev)
		}
	}
	s.mu.Unlock()

	fromSec := now.Add(-d).Unix()
	first := fromSec + floorMod(-fromSec, stepSec) // aligned up to the step grid
	last := now.Unix() - floorMod(now.Unix(), stepSec)
	if last < first {
		return nil
	}
	steps := (last-first)/stepSec + 1
	total := steps * int64(len(devs))
	started := time.Now()
	s.log.Info("backfilling synthetic history",
		"from", unix(first), "to", unix(last), "step", step, "devices", len(devs), "rows", total)

	prev := make([]prevCounters, len(devs))
	batch := make([]model.Sample, 0, backfillBatch)
	var inserted int64
	nextReport := int64(0)
	flush := func() error {
		if len(batch) == 0 {
			return nil
		}
		if err := st.InsertSamples(ctx, batch); err != nil {
			return fmt.Errorf("demo: backfill: insert samples: %w", err)
		}
		inserted += int64(len(batch))
		batch = batch[:0]
		if inserted >= nextReport {
			s.log.Info("backfill progress", "rows", inserted, "total", total,
				"pct", int(100*inserted/total), "elapsed", time.Since(started).Round(time.Millisecond))
			nextReport += total / 4
		}
		return nil
	}

	for ts := first; ts <= last; ts += stepSec {
		if err := ctx.Err(); err != nil {
			return fmt.Errorf("demo: backfill: %w", err)
		}
		t := unix(ts)
		s.mu.Lock()
		for i, dev := range devs {
			batch = append(batch, s.sample(dev, t, &prev[i], stepSec))
		}
		s.mu.Unlock()
		if len(batch) >= backfillBatch {
			if err := flush(); err != nil {
				return err
			}
		}
	}
	if err := flush(); err != nil {
		return err
	}

	firstSeen := unix(first)
	s.mu.Lock()
	mdevs := make([]model.Device, 0, len(devs))
	for _, dev := range devs {
		if dev.deleted {
			continue
		}
		md := s.modelDevice(dev, now)
		md.FirstSeen = firstSeen
		mdevs = append(mdevs, md)
	}
	s.mu.Unlock()
	if err := st.UpsertDevices(ctx, mdevs); err != nil {
		return fmt.Errorf("demo: backfill: upsert devices: %w", err)
	}
	s.log.Info("backfill complete", "rows", inserted, "devices", len(mdevs),
		"elapsed", time.Since(started).Round(time.Millisecond))
	return nil
}

// sample builds the raw sample for dev at t. prev carries the counters of
// the previous step so rates are computed the way the collector does.
// s.mu must be held.
func (s *Sim) sample(dev *device, t time.Time, prev *prevCounters, stepSec int64) model.Sample {
	in := s.instantAt(dev, t, false)
	sm := model.Sample{DeviceID: dev.id, TS: t, Online: in.online}
	isSelf := dev == s.self
	inNetmap := dev.authorized && !isSelf

	rate := func(f int) float64 {
		if prev.ok {
			delta := in.counters[f] - prev.counters[f]
			if delta < 0 {
				return 0
			}
			return delta / float64(stepSec)
		}
		return in.rates[f]
	}

	if isSelf {
		sm.Online = true
	}
	if inNetmap {
		sm.TSRxBytes = int64(in.counters[flowPeerRx])
		sm.TSTxBytes = int64(in.counters[flowPeerTx])
		sm.TSRxRate = rate(flowPeerRx)
		sm.TSTxRate = rate(flowPeerTx)
		if in.online {
			lat := in.latency
			sm.LatencyMs = &lat
			direct := dev.direct
			sm.Direct = &direct
			if !direct {
				sm.Relay = dev.relay
			}
		}
	}
	if (isSelf || (inNetmap && in.online)) && dev.agent == agentYes {
		sm.AgentOK = true
		cpu, mem, disk, load1 := roundTo(in.cpu, 0.1), roundTo(in.mem, 0.1), roundTo(in.disk, 0.1), roundTo(in.load1, 0.01)
		rx, tx := rate(flowPhysRx), rate(flowPhysTx)
		up := in.uptime
		sm.CPU, sm.Mem, sm.Disk, sm.Load1 = &cpu, &mem, &disk, &load1
		sm.NetRxRate, sm.NetTxRate = &rx, &tx
		sm.Uptime = &up
		if dev.hasSensors() {
			temp := roundTo(in.temp, 0.1)
			sm.TempC = &temp
		}
	}
	prev.ok = true
	prev.counters = in.counters
	return sm
}
